export const API_ROUTE = {
  LOGIN: '/api/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot_password',
  RESET_PASSWORD: '/reset_password',
  GET_USER_INFO: '/get_user_info',
  UPDATE_USER_INFO: '/update_user_info',
  GET_USER_LIST: '/get_user_list',
  GET_USER_BY_ID: '/get_user_by_id',
  GET_USER_BY_EMAIL: '/get_user_by_email',
  GET_USER_BY_PHONE: '/get_user_by_phone',
  GET_USER_BY_NAME: '/get_user_by_name',
  UPDATE_USER_STATUS: '/update_user_status',
  UPDATE_USER_ROLE: '/api/update_user_role',
  UPDATE_USER_PASSWORD: '/update_user_password',
  UPDATE_USER_AVATAR: '/chatservice/api/update_user_avatar',
  UPDATE_USER_LANGUAGE: '/chatservice/api/update_user_language',
  UPDATE_USER_BIO: '/chatservice/api/update_user_bio',
  UPDATE_USER_PHONE: '/chatservice/api/update_user_phone',
  UPDATE_USER_EMAIL: '/chatservice/api/update_user_email',
  GET_USER_BY_SEARCH: '/chatservice/api/get_user_by_search',
  GET_ALL_GROUPS: '/chatservice/api/get_all_groups',
  GET_GROUP_BY_ID: '/chatservice/api/get_group_by_id',
  GET_GROUP_BY_NAME: '/chatservice/api/get_group_by_name',
  GET_GROUP_BY_ADMIN: '/chatservice/api/get_group_by_admin',
  GET_CONVERTSTATION_CHAT: 'api/chatservice/get_convertstation',
  SEND_MESSAGE: 'api/chatservice/sendmessage',
  REFRESH_TOKEN: '/api/user/refreshtoken',
  GET_LIST_FRIEND_CHAT: 'api/chatservice/friendchat',
  CREATE_CONVERSTATION: 'api/chatservice/create_converstaion',
  DELETE_CONVERSTATION: 'api/chatservice/delete_converstation',
  UPDATE_MESSAGE: 'api/chatservice/update_message',
  DELATE_MESSAGE: 'api/chatservice/delete_message',
  RECALL_MESSAGE:'api/chatservice/recall_message'
};